name: CI
on:
  push:
    branches: [ master ]    
  pull_request:
    branches: [ master ]
    
jobs:  
  build:    
    runs-on: windows-latest
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4      
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Fetch History
        run: git fetch --prune --unshallow      
        
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
            versionSpec: '5.x'
            
      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        
      - name: Print GitVersion
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        
      - name: Restore NuGet Packages
        run: nuget restore GodotTemplates.sln
        
      - name: Build Solution
        run: msbuild GodotTemplates.sln /p:Configuration=Release              
