name: CI
on:
  push:
    branches: [ master ]    
  pull_request:
    branches: [ master ]
    
env:
  test: ciao
    
jobs:  
  build:    
    runs-on: windows-latest
    outputs:      
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}   
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4    
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
            versionSpec: '5.x'
            
      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        
      - name: Print GitVersion
        run: |
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"              
